web:
  image: vamsiammineni/myflaskapp:latest
  command: python -u main.py
  ports:
    - 5000:5000
  links:
    - db
db:
  image: mongo:3.0.2
  ports:
    - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet